# -*- coding: utf-8 -*-
"""Digest ChatGPT (round1) — недостающая часть B_100 (Реплит добавил только
источники и штампы deep_researched, но не перенёс содержательные факты из того
же дайджеста — см. журнал 14 августа). 42 правки полей + источники, дословно
сверенные с реально скачанным текстом.
"""

FIXES = [
    dict(id='gd88cbe9a', field='eco.context', old='—',
         new='Прежним собственником «Гейзер Голд» было ООО «Гиперспэйс»',
         quote='Прежним собственником «Гейзер Голд» было ООО «Гиперспэйс»',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/7796300'),
    dict(id='g042073c4', field='law.struct', old='—',
         new='АФК «Система» сохранила за собой контрольный пакет',
         quote='АФК «Система» сохранила за собой контрольный пакет',
         why='из digest ChatGPT round1 (B_100), сверено с https://pravo.ru/company_news/259172/'),
    dict(id='g042073c4', field='law.terms', old='—',
         new='В том числе ключевые кредиторы лесопромышленного холдинга.',
         quote='в том числе ключевые кредиторы лесопромышленного холдинга.',
         why='из digest ChatGPT round1 (B_100), сверено с https://pravo.ru/company_news/259172/'),
    dict(id='gdab53817', field='law.struct', old='—',
         new='Инвесторам предлагается доля в размере 16,5% капитала компании',
         quote='инвесторам предлагается доля в размере 16,5% капитала компании',
         why='из digest ChatGPT round1 (B_100), сверено с https://incrussia.ru/news/finteh-platforma-invojskafe-obyavila-o-privlechenii-investitsij/'),
    dict(id='gdab53817', field='eco.val', old='—',
         new='Предынвестиционная стоимость бизнеса составляет 760 млн руб.',
         quote='предынвестиционная стоимость бизнеса составляет 760 млн руб.',
         why='из digest ChatGPT round1 (B_100), сверено с https://incrussia.ru/news/finteh-platforma-invojskafe-obyavila-o-privlechenii-investitsij/'),
    dict(id='g076a2f4e', field='law.appr', old='Публично не сообщалось',
         new='Федеральная антимонопольная служба согласовала ходатайство девелопера GloraX по покупке пяти застройщиков в Приморском крае.',
         quote='Федеральная антимонопольная служба согласовала ходатайство девелопера GloraX по покупке пяти застройщиков в Приморском крае.',
         why='из digest ChatGPT round1 (B_100), сверено с https://dvizhenie.ru/media/3363/fas-soglasovala-pokupku-developerom-glorax-pyati-zastrojshikov-v-primore'),
    dict(id='g076a2f4e', field='eco.target_fin', old='—',
         new='Объем продаж ГК «Жилкапинвест» с начала 2025 года составил 7,9 тыс. кв. м или 1,2 млрд руб.',
         quote='Объем продаж ГК «Жилкапинвест» с начала 2025 года составил 7,9 тыс. кв. м или 1,2 млрд руб.',
         why='из digest ChatGPT round1 (B_100), сверено с https://glorax.com/press-center/news/glorax-obyavlyaet-onbsppriobretenii-developerskoj'),
    dict(id='c299076c8', field='eco.target_fin', old=None,
         new='Объем продаж ГК «Жилкапинвест» с начала 2025 года составил 7,9 тыс. кв. м или 1,2 млрд руб. в денежном выражении.',
         quote='Объем продаж ГК «Жилкапинвест» с начала 2025 года составил 7,9 тыс. кв. м или 1,2 млрд руб. в денежном выражении.',
         why='из digest ChatGPT round1 (B_100), сверено с https://glorax.com/press-center/news/glorax-obyavlyaet-onbsppriobretenii-developerskoj'),
    dict(id='g549ddd5a', field='law.struct', old='—',
         new='Доля ГК «Эфко» в «Масленице», вырастет с текущих 31,4% до 100%.',
         quote='Доля ГК «Эфко» в «Масленице», вырастет с текущих 31,4% до 100%.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.sostav.ru/publication/gk-efko-pokupaet-proizvoditelya-olejny-76286.html'),
    dict(id='g549ddd5a', field='eco.val', old='—',
         new='Оценка инвестбанкира Ильи Шумова - 18-20 млрд рублей.',
         quote='Оценка инвестбанкира Ильи Шумова - 18-20 млрд рублей.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.interfax.ru/russia/1033832'),
    dict(id='ge2e2c71c', field='eco.context', old='—',
         new='ЕАГ не раскрывает владельцев, но прежде основным собственником был Отар Балинов.',
         quote='ЕАГ не раскрывает владельцев, но прежде основным собственником был Отар Балинов.',
         why='из digest ChatGPT round1 (B_100), сверено с https://shoppers.media/news/26587_vladelec-brenda-santo-stefano-gotovitsia-vypustit-krepkie-kokteili'),
    dict(id='gca9cd4b7', field='eco.target_fin', old='—',
         new='За 2024 год прибыль компании составляет — -5 079 000 ₽, выручка за 2024 год — 679 510 000 ₽.',
         quote='За 2024 год прибыль компании составляет — -5 079 000 ₽, выручка за 2024 год — 679 510 000 ₽.',
         why='из digest ChatGPT round1 (B_100), сверено с https://companies.rbc.ru/id/1064816020279-ooo-moskva-na-donu/'),
    dict(id='g016f1b13', field='eco.val', old='—',
         new='Оценочная стоимость нового актива, взятого в управление, составляет от 6 до 7 млрд рублей.',
         quote='Оценочная стоимость нового актива, взятого в управление, составляет от 6 до 7 млрд рублей.',
         why='из digest ChatGPT round1 (B_100), сверено с https://ibcrealestate.ru/history/odin-iz-krupneyshikh-gostinichnykh-kompleksov-podmoskovya-pereshel-pod-upravlenie-kompanii-vizant/'),
    dict(id='g09242ae2', field='eco.target_fin', old='—',
         new='По итогам 2024 года выручка составила 626,5 млн рублей, чистая прибыль — 7 млн рублей.',
         quote='по итогам 2024 года выручка составила 626,5 млн рублей, чистая прибыль — 7 млн рублей.',
         why='из digest ChatGPT round1 (B_100), сверено с https://agrovesti.net/news/corp/plodorodie-priobrelo-agroaktivy-kontserna-detskoselskij-v-voronezhskoj-oblasti.html'),
    dict(id='gf9932079', field='eco.target_fin', old='—',
         new='Выручка АО «Издательство «Просвещение»» по РСБУ в 2024 году составила 51,1 млрд руб.',
         quote='Выручка АО «Издательство «Просвещение» по РСБУ в 2024 году составила 51,1 млрд руб.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.interfax.ru/business/1045712'),
    dict(id='g381ff192', field='eco.target_fin', old='—',
         new='В 2024 году выручка БСК составила 61 млрд руб., чистая прибыль — 4,6 млрд руб.',
         quote='В 2024 году выручка БСК составила 61 млрд руб., чистая прибыль — 4,6 млрд руб.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/7777916'),
    dict(id='g8ed07ff5', field='law.appr', old='—',
         new='Предварительное согласие на покупку акций ранее выдала Федеральная антимонопольная служба РФ.',
         quote='Предварительное согласие на покупку акций ранее выдала Федеральная антимонопольная служба РФ.',
         why='из digest ChatGPT round1 (B_100), сверено с https://zolteh.ru/news/gruppa_okto_priobrela_100_aktsiy_zolotodobyvayushchey_gk_zapadnaya/'),
    dict(id='g5d835058', field='eco.target_fin', old='—',
         new='По итогам 2024 года выручка юрлиц «РУСMED» составила 389 млн рублей.',
         quote='По итогам 2024 года выручка юрлиц «РУСMED» составила 389 млн рублей.',
         why='из digest ChatGPT round1 (B_100), сверено с https://vademec.ru/news/2025/05/22/gk-medsi-priobrela-kliniku-v-nizhnem-novgorode-za-450-mln-rubley/'),
    dict(id='g2a3a597b', field='law.struct', old='—',
         new='Инвесторам будут предложены акции новой эмиссии объемом до 15%',
         quote='Инвесторам будут предложены акции новой эмиссии объемом до 15%',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/7532986'),
    dict(id='g2a3a597b', field='eco.target_fin', old='—',
         new='Выручка в 2024 году по собственным данным –19 млрд рублей, EBITDA – 1,4 млрд рублей.',
         quote='Выручка в 2024 году по собственным данным –19 млрд рублей, EBITDA – 1,4 млрд рублей.',
         why='из digest ChatGPT round1 (B_100), сверено с https://newprospect.ru/news/sozdatel-brenda-baltijskij-bereg-xochet-privlech-45-mlrd-rublej-na-pre-ipo'),
    dict(id='g91ec3558', field='law.appr', old='Публично не сообщалось',
         new='Сделку одобрила Федеральная антимонопольная служба (ФАС)',
         quote='Сделку одобрила Федеральная антимонопольная служба (ФАС)',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.rbc.ru/business/05/05/2025/681874769a7947864a3eee7a'),
    dict(id='cc2929a95', field='law.struct', old=None,
         new='Приобретение до 100% голосующих акций МКАО «Западная Голд Майнинг Лимитед».',
         quote='приобретение до 100% голосующих акций МКАО «Западная Голд Майнинг Лимитед».',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.rbc.ru/business/25/04/2025/680b35279a79473cf11967ae'),
    dict(id='cc2929a95', field='law.appr', old=None,
         new='Сопровождала получение согласия ФАС России на совершение сделки',
         quote='сопровождала получение согласия ФАС России на совершение сделки',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.level-legal.com/news/yuridicheskaya-firma-level-legal-services-osushestvila-kompleksnoe-yuridicheskoe-konsultirovanie-chastnogo-investora-v-svyazi-s-priobreteniem-gk-zapadnaya'),
    dict(id='cc2929a95', field='eco.target_fin', old=None,
         new='ГРК «Западная» производит около 3 тонн золота в год',
         quote='ГРК «Западная» производит около 3 тонн золота в год',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/8077927'),
    dict(id='gaa82c6f6', field='eco.target_fin', old='—',
         new='Собственный капитал банка оценивался в 3,48 млрд руб.',
         quote='собственный капитал банка оценивался в 3,48 млрд руб.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/7476881'),
    dict(id='g9b746362', field='law.terms', old='—',
         new='Увеличение пакета до контрольного компания не планирует.',
         quote='увеличение пакета до контрольного компания не планирует.',
         why='из digest ChatGPT round1 (B_100), сверено с https://a-pi.ru/news/20250516/'),
    dict(id='g1a475dee', field='law.terms', old='—',
         new='Были проработаны ключевые аспекты будущего партнёрства, включая финансовые механизмы, структуру корпоративного управления и принципы совместной деятельности.',
         quote='были проработаны ключевые аспекты будущего партнёрства, включая финансовые механизмы, структуру корпоративного управления и принципы совместной деятельности.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.level-legal.com/news/yuridicheskaya-firma-level-legal-services-soprovodila-sdelku-po-investirovaniyu-gruppy-arenadata-v-razrabotchika-mdm-reshenij'),
    dict(id='g7596ae81', field='law.appr', old='Публично не сообщалось',
         new='Сделка была одобрена подкомиссией Правительственной комиссии по контролю за осуществлением иностранных инвестиций',
         quote='Сделка была одобрена подкомиссией Правительственной комиссии по контролю за осуществлением иностранных инвестиций',
         why='из digest ChatGPT round1 (B_100), сверено с https://kamacapital.ru/news/28/'),
    dict(id='g7596ae81', field='law.struct', old='—',
         new='Формат сделки: купля-продажа долей и акций в компаниях—собственниках активов',
         quote='Формат сделки: купля-продажа долей и акций в компаниях—собственниках активов',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/8077927'),
    dict(id='gd4645195', field='eco.context', old='—',
         new='Осенью 2024-го S8 Capital перепродал бизнес Bosch «Севергрупп».',
         quote='осенью 2024-го S8 Capital перепродал бизнес Bosch «Севергрупп».',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.rbc.ru/business/25/06/2025/685aaa979a7947353b2c6c4d'),
    dict(id='gd4645195', field='eco.val', old='—',
         new='Чистых активов, которые на конец 2023 года составляли 804 млн руб.',
         quote='чистых активов, которые на конец 2023 года составляли 804 млн руб.',
         why='из digest ChatGPT round1 (B_100), сверено с https://mergers.ru/news/Severgrupp-Mordashova-prodala-OOO-Jengels-Jelektroinstrumenty-byvshij-zavod-Bosch-85439'),
    dict(id='g0924279f', field='law.struct', old='—',
         new='Дмитрий Хотимский получил 50% в ООО «Полипап», разделив бизнес с основателем компании Пётр Кабин',
         quote='Дмитрий Хотимский получил 50% в ООО «Полипап», разделив бизнес с основателем компании Пётр Кабин',
         why='из digest ChatGPT round1 (B_100), сверено с https://sfera.fm/news/fud-reteil/soosnovatel-sovkombanka-priobrel-50-biznesa-po-proizvodstvu-bumazhnykh-stakanov'),
    dict(id='g0924279f', field='eco.val', old='—',
         new='Участники рынка оценивают её в диапазоне 150–300 млн рублей.',
         quote='участники рынка оценивают её в диапазоне 150–300 млн рублей.',
         why='из digest ChatGPT round1 (B_100), сверено с https://sfera.fm/news/fud-reteil/soosnovatel-sovkombanka-priobrel-50-biznesa-po-proizvodstvu-bumazhnykh-stakanov'),
    dict(id='g4e3ec471', field='law.struct', old='—',
         new='Покупку 100% долей у закрытого паевого инвестиционного фонда «Азимут-капитал»',
         quote='покупку 100% долей у закрытого паевого инвестиционного фонда «Азимут-капитал»',
         why='из digest ChatGPT round1 (B_100), сверено с https://orion-law.com/news/komanda-orion-konsultirovala-ooo-sberbank-investicii-v-sdelke-po-priobreteniyu-100-dolej-ooo-sdm-tk-2-i-dalnejshej-prodazhe-50-dolej-ooo-logopark-7'),
    dict(id='ce1b2321f', field='law.struct', old=None,
         new='Размер пакета акций/долей: 100',
         quote='Размер пакета акций/долей: 100',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/8077927'),
    dict(id='gf3c5069f', field='law.appr', old='Публично не сообщалось',
         new='Это предложение Минфина, согласованное с Росимуществом.',
         quote='это предложение Минфина, согласованное с Росимуществом.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/7552771'),
    dict(id='g7d64b437', field='eco.target_fin', old='—',
         new='Чистая прибыль выросла на 174% до 1.34 млрд руб.',
         quote='Чистая прибыль выросла на 174% до 1.34 млрд руб.',
         why='из digest ChatGPT round1 (B_100), сверено с https://cbonds.ru/news/3347993/'),
    dict(id='g5880d206', field='eco.context', old='—',
         new='Ранее Фольксваген Банк Гмбх владел 1%, Фольксваген Файненшл Сервисез Оверсиз Акциенгезелльшафт — 99%.',
         quote='Ранее Фольксваген Банк Гмбх владел 1%, Фольксваген Файненшл Сервисез Оверсиз Акциенгезелльшафт — 99%.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.akm.ru/news/folksvagen_bank_rus_smenil_vladeltsa/'),
    dict(id='g5880d206', field='eco.val', old='—',
         new='Оценивает «Метрополис» в 60–65 млрд руб.',
         quote='оценивает «Метрополис» в 60–65 млрд руб.',
         why='из digest ChatGPT round1 (B_100), сверено с https://www.kommersant.ru/doc/8400478'),

    # источники
    dict(id='gd88cbe9a', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/7796300'],
         quote='Прежним собственником «Гейзер Голд» было ООО «Гиперспэйс»',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g042073c4', field='src', old=None,
         new=['pravo.ru', 'https://pravo.ru/company_news/259172/'],
         quote='АФК «Система» сохранила за собой контрольный пакет',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='gdab53817', field='src', old=None,
         new=['incrussia.ru', 'https://incrussia.ru/news/finteh-platforma-invojskafe-obyavila-o-privlechenii-investitsij/'],
         quote='инвесторам предлагается доля в размере 16,5% капитала компании',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='gdab53817', field='src', old=None,
         new=['t.me', 'https://t.me/s/rusven?before=6856'],
         quote='размещение проходит на инвестплатформе ВТБ Регистратора',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g076a2f4e', field='src', old=None,
         new=['dvizhenie.ru', 'https://dvizhenie.ru/media/3363/fas-soglasovala-pokupku-developerom-glorax-pyati-zastrojshikov-v-primore'],
         quote='Федеральная антимонопольная служба согласовала ходатайство девелопера GloraX по покупке пяти застройщиков в Приморском крае.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g076a2f4e', field='src', old=None,
         new=['Glorax', 'https://glorax.com/press-center/news/glorax-obyavlyaet-onbsppriobretenii-developerskoj'],
         quote='Объем продаж ГК «Жилкапинвест» с начала 2025 года составил 7,9 тыс. кв. м или 1,2 млрд руб.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='c299076c8', field='src', old=None,
         new=['Glorax', 'https://glorax.com/press-center/news/glorax-obyavlyaet-onbsppriobretenii-developerskoj'],
         quote='Объем продаж ГК «Жилкапинвест» с начала 2025 года составил 7,9 тыс. кв. м или 1,2 млрд руб. в денежном выражении.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g549ddd5a', field='src', old=None,
         new=['Sostav.ru', 'https://www.sostav.ru/publication/gk-efko-pokupaet-proizvoditelya-olejny-76286.html'],
         quote='Доля ГК «Эфко» в «Масленице», вырастет с текущих 31,4% до 100%.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g549ddd5a', field='src', old=None,
         new=['Интерфакс', 'https://www.interfax.ru/russia/1033832'],
         quote='Оценка инвестбанкира Ильи Шумова - 18-20 млрд рублей.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='ge2e2c71c', field='src', old=None,
         new=['shoppers.media', 'https://shoppers.media/news/26587_vladelec-brenda-santo-stefano-gotovitsia-vypustit-krepkie-kokteili'],
         quote='ЕАГ не раскрывает владельцев, но прежде основным собственником был Отар Балинов.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='gca9cd4b7', field='src', old=None,
         new=['РБК Компании', 'https://companies.rbc.ru/id/1064816020279-ooo-moskva-na-donu/'],
         quote='За 2024 год прибыль компании составляет — -5 079 000 ₽, выручка за 2024 год — 679 510 000 ₽.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g016f1b13', field='src', old=None,
         new=['ibcrealestate.ru', 'https://ibcrealestate.ru/history/odin-iz-krupneyshikh-gostinichnykh-kompleksov-podmoskovya-pereshel-pod-upravlenie-kompanii-vizant/'],
         quote='Оценочная стоимость нового актива, взятого в управление, составляет от 6 до 7 млрд рублей.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g09242ae2', field='src', old=None,
         new=['agrovesti.net', 'https://agrovesti.net/news/corp/plodorodie-priobrelo-agroaktivy-kontserna-detskoselskij-v-voronezhskoj-oblasti.html'],
         quote='по итогам 2024 года выручка составила 626,5 млн рублей, чистая прибыль — 7 млн рублей.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='gf9932079', field='src', old=None,
         new=['Интерфакс', 'https://www.interfax.ru/business/1045712'],
         quote='Выручка АО «Издательство «Просвещение» по РСБУ в 2024 году составила 51,1 млрд руб.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g381ff192', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/7777916'],
         quote='В 2024 году выручка БСК составила 61 млрд руб., чистая прибыль — 4,6 млрд руб.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g8ed07ff5', field='src', old=None,
         new=['zolteh.ru', 'https://zolteh.ru/news/gruppa_okto_priobrela_100_aktsiy_zolotodobyvayushchey_gk_zapadnaya/'],
         quote='Предварительное согласие на покупку акций ранее выдала Федеральная антимонопольная служба РФ.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g5d835058', field='src', old=None,
         new=['vademec.ru', 'https://vademec.ru/news/2025/05/22/gk-medsi-priobrela-kliniku-v-nizhnem-novgorode-za-450-mln-rubley/'],
         quote='По итогам 2024 года выручка юрлиц «РУСMED» составила 389 млн рублей.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g2a3a597b', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/7532986'],
         quote='Инвесторам будут предложены акции новой эмиссии объемом до 15%',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g2a3a597b', field='src', old=None,
         new=['newprospect.ru', 'https://newprospect.ru/news/sozdatel-brenda-baltijskij-bereg-xochet-privlech-45-mlrd-rublej-na-pre-ipo'],
         quote='Выручка в 2024 году по собственным данным –19 млрд рублей, EBITDA – 1,4 млрд рублей.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='cc2929a95', field='src', old=None,
         new=['LEVEL Legal Services', 'https://www.level-legal.com/news/yuridicheskaya-firma-level-legal-services-osushestvila-kompleksnoe-yuridicheskoe-konsultirovanie-chastnogo-investora-v-svyazi-s-priobreteniem-gk-zapadnaya'],
         quote='сопровождала получение согласия ФАС России на совершение сделки',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='cc2929a95', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/8077927'],
         quote='ГРК «Западная» производит около 3 тонн золота в год',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='gaa82c6f6', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/7476881'],
         quote='собственный капитал банка оценивался в 3,48 млрд руб.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g9b746362', field='src', old=None,
         new=['a-pi.ru', 'https://a-pi.ru/news/20250516/'],
         quote='увеличение пакета до контрольного компания не планирует.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g1a475dee', field='src', old=None,
         new=['LEVEL Legal Services', 'https://www.level-legal.com/news/yuridicheskaya-firma-level-legal-services-soprovodila-sdelku-po-investirovaniyu-gruppy-arenadata-v-razrabotchika-mdm-reshenij'],
         quote='были проработаны ключевые аспекты будущего партнёрства, включая финансовые механизмы, структуру корпоративного управления и принципы совместной деятельности.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g7596ae81', field='src', old=None,
         new=['kamacapital.ru', 'https://kamacapital.ru/news/28/'],
         quote='Сделка была одобрена подкомиссией Правительственной комиссии по контролю за осуществлением иностранных инвестиций',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g7596ae81', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/8077927'],
         quote='Формат сделки: купля-продажа долей и акций в компаниях—собственниках активов',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='gd4645195', field='src', old=None,
         new=['Mergers.ru', 'https://mergers.ru/news/Severgrupp-Mordashova-prodala-OOO-Jengels-Jelektroinstrumenty-byvshij-zavod-Bosch-85439'],
         quote='чистых активов, которые на конец 2023 года составляли 804 млн руб.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g0924279f', field='src', old=None,
         new=['sfera.fm', 'https://sfera.fm/news/fud-reteil/soosnovatel-sovkombanka-priobrel-50-biznesa-po-proizvodstvu-bumazhnykh-stakanov'],
         quote='Дмитрий Хотимский получил 50% в ООО «Полипап», разделив бизнес с основателем компании Пётр Кабин',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g4e3ec471', field='src', old=None,
         new=['orion-law.com', 'https://orion-law.com/news/komanda-orion-konsultirovala-ooo-sberbank-investicii-v-sdelke-po-priobreteniyu-100-dolej-ooo-sdm-tk-2-i-dalnejshej-prodazhe-50-dolej-ooo-logopark-7'],
         quote='покупку 100% долей у закрытого паевого инвестиционного фонда «Азимут-капитал»',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='ce1b2321f', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/8077927'],
         quote='Размер пакета акций/долей: 100',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='gf3c5069f', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/7552771'],
         quote='это предложение Минфина, согласованное с Росимуществом.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g7d64b437', field='src', old=None,
         new=['cbonds.ru', 'https://cbonds.ru/news/3347993/'],
         quote='Чистая прибыль выросла на 174% до 1.34 млрд руб.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g5880d206', field='src', old=None,
         new=['АКМ', 'https://www.akm.ru/news/folksvagen_bank_rus_smenil_vladeltsa/'],
         quote='Ранее Фольксваген Банк Гмбх владел 1%, Фольксваген Файненшл Сервисез Оверсиз Акциенгезелльшафт — 99%.',
         why='источник из digest ChatGPT round1 (B_100)'),
    dict(id='g5880d206', field='src', old=None,
         new=['Коммерсантъ', 'https://www.kommersant.ru/doc/8400478'],
         quote='оценивает «Метрополис» в 60–65 млрд руб.',
         why='источник из digest ChatGPT round1 (B_100)'),
]